### ISSUE TITLE
Do not display the site

### ISSUE THREAD

**Issue by shahriaarrr** [BlackIQ/markdown#4]
![image](https://user-images.githubusercontent.com/75499598/138583206-921010d1-1b55-4545-94f2-f34c15af33cc.png)

**Comment by BlackIQ** [comment]
یه پیام دارم برای شهریار عزیز. برو درت رو بزار دست از سر ما بردار. به تو ربطی نداره این باز میشه یا نه. به جای این که بری اونو ببینی بیا اینو بابا اسگل.

تو یه اسکی زنی بابا. ریدم تو سرور دیسکورد و چنل یوتیوبت. کسخل خر.

ایشو باز کنی، پول بزنی روی ریپو های این اکانت گوه میخوری بزاری.

برو گمشو نبینمت.

**Comment by shahriaarrr** [comment]
پیشنهاد میکنم بجای برنامه نویسی یک کم درس شعور اجتماعی بخونی.علمت از من بیشتره در این شکی نیست و سن هم ربطی به علم نداره ولی وقتی سنت از من کمتره با این ادبیات نباید صحبت کنی وقتی با این ادبیات باهات صحبت نکردم.امیدوارم همونطور که در زمینه کاریت پیشرفت میکنی در زمینه شعور و رفتار اجتماعی هم پیشرفت کنی.رفاقت با تو باعث افتخار بود برام✌❤💣

**Comment by BlackIQ** [comment]
همینه که هست.

آدرس پیج ها:

https://md.blackiq.ir/fa
https://md.blackiq.ir/en
